### PR TITLE
use 1998-cmo-2 algorithm to improve speed of point add and point double

### PR DESCRIPTION
**Pull request by FullyRobert**
The point add(PA) and point double(PD) algorithms in libsm are named add-1998-cmo and double-1998-cmo. The time consume of these algorithmS are 10M + 5S + 4cubic = 23M and 3M + 3S + 2^4 = 12M . According to website [https://www.hyperelliptic.org/EFD/g1p/auto-shortw-jacobian.html#addition-add-1998-cmo-2](https://www.hyperelliptic.org/EFD/g1p/auto-shortw-jacobian.html#addition-add-1998-cmo-2), the fastest PA and PD  named add-1998-cmo-2 and double-1998-cmo-2 only need 16M and 9M.

After replacing new algorithms, the time consume  of PA and PD decreased by 35% and 15% respectively. I use criterion to compare the speed before and after the improvement. It must be noted that the optimization efficiency will be different when PA and PD calculate different points

PA:

> Ecc add             time:   [1.3219 us 1.3611 us 1.4074 us]                          
>                         change: [-47.407% -45.710% -43.853%] (p = 0.00 < 0.05)
>                         Performance has improved.

Test code:
``` rust
fn ecc_add(c: &mut Criterion) {
    let curve = EccCtx::new();
    let g = curve.generator();
    let neg_g = curve.neg(&g);
    let double_g = curve.double(&g);
    c.bench_function("Ecc old add ", move |b| {
        b.iter(|| curve.add(&double_g, &neg_g));
    });
}
``` 
PD:

> Ecc double              time:   [1.1666 us 1.1969 us 1.2322 us]                         
>                         change: [-19.976% -18.640% -16.936%] (p = 0.00 < 0.05)
>                         Performance has improved.

Test code:
``` rust
fn ecc_double(c: &mut Criterion) {
    let curve = EccCtx::new();
    let g = curve.generator();

    c.bench_function("Ecc double ", move |b| {
        b.iter(|| curve.double(&g));
    });
}
```

### CODE REVIEW

**Comment by Pencil-Yao** [comment]
Thank for your pr, I will test it soon.

**Comment by Pencil-Yao** [comment]
Thanks for your contribution. Nice job

**Review by Pencil-Yao — APPROVED** [review]

**Comment by Pencil-Yao** [comment]
If you have interest on performance maybe you would like to look [efficient-sm2](https://github.com/Pencil-Yao/efficient-sm2) which we replace `libsm`

**Comment by FullyRobert** [comment]
thank you for your advice

**Pull request merged**
