### PR TITLE
replace mul with gmul in pk_from_sk function

### PR DESCRIPTION
**Pull request by FullyRobert**
It's not necessary to use expensive mul operations in pk_from_sk functions, replacing it with g_mul can reduce execution time

### CODE REVIEW

**Comment by Pencil-Yao** [comment]
Thank you, but have conflict due to previous commit.

**Comment by FullyRobert** [comment]
ok，maybe i should close this pr and open a new pr

**Comment by Pencil-Yao** [comment]
I wait you.

**Comment by FullyRobert** [comment]
done.

**Pull request closed without merging**
